project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!files/"
  resources:
    - "*.json"
    - "files"
    - "_extensions"

execute:
  freeze: auto


website:
  repo-url: https://github.com/inqs909/m201_s26
  title: "MATH 201"
  site-url: www.inqs.info/m201_s26
  favicon: "img/favicon/favicon.svg"
  navbar:
    logo: "img/favicon/favicon.svg" 
    right:
      - syllabus.qmd
      - lectures.qmd
      - rcode.qmd
      - ec.qmd

format:
  html:
    theme: 
      light: theme.scss
    toc: true



